### ISSUE TITLE
Incorrect lemma and features for some roman numerals

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-PUD#36]
The following should be `CD` with `NumType=Ord|NumForm=Roman`:
```
ERROR: Sentence n01011011 token 5 -- NNP lemma 'III' does not match capitalized-form applied to form 'III', expected 'Iii'
WARN: Sentence w02014030 token 10 -- CD lemma 'i.' does not have a validation rule for form 'I.'
```

In both cases, the lemma should match the form text.

**Comment by AngledLuffa** [comment]
Mind updating your validator to supply the features in alphabetical order?  I believe this is correct:

`NumForm=Roman|NumType=Ord`

**Comment by rhdunn** [comment]
Ah, that was me interpeting the results of the validator :). -- Yes, the features should be sorted per one of the main UD validation scripts.

**Comment by rhdunn** [comment]
Closing as fixed.
