### ISSUE TITLE
Incorrect use of VBP on the verb "thought"

### ISSUE THREAD

**Issue by rhdunn** [UniversalDependencies/UD_English-PUD#38]
```
ERROR: Sentence w01124011 token 14 -- VBP lemma 'think' does not match lowercase-form applied to form 'Thought', expected 'thought'
```

Here, "thought" is either past tense ("VBD" -ing) or is the past participle ("VBN" -en/-ed). It is not the singular present ("VBP").

**Comment by AngledLuffa** [comment]
Surely that would be something like "I Thought You Knew" and therefore VBD, not VBN?

while we're there, lemmatize `'ya` as `you`?

**Comment by rhdunn** [comment]
I was trying to say that it should not be VBP but should be VBD *or* VBN. -- I wasn't confident to say which :)!

**Comment by AngledLuffa** [comment]
I like the VBD, as if there's an unseen person saying "I thought you knew"

**Comment by rhdunn** [comment]
Closing as fixed.
