### ISSUE TITLE
Validation error: NUM with NumType=Ord

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-PUD#47]
NumType=Ord is only allowed on adjectives. There are two violations:

https://github.com/UniversalDependencies/UD_English-PUD/blob/1b118499e4b36aba4f0b43b90d363b8311c787ec/en_pud-ud-test.conllu#L570

"Andre Price III"—for such generational suffixes in EWT, we have been using `NumType=Card` (though it may well be *pronounced* as "the third", neither the determiner nor the ordinal suffix is written).

https://github.com/UniversalDependencies/UD_English-PUD/blob/1b118499e4b36aba4f0b43b90d363b8311c787ec/en_pud-ud-test.conllu#L22326

"King Franz Joseph I."—regnal suffixes are generally `NumType=Card`, but perhaps the period indicates it is ordinal—maybe it was accidentally retained in translation from German? As far as English spelling rules are concerned I'd consider it a typo.

**Comment by nschneid** [comment]
@dan-zeman Do you know why the update I just pushed hasn't fixed the validation error?

**Comment by dan-zeman** [comment]
> I'd consider it a typo

Note that unlike in other UD treebanks, in PUD we don't annotate typos in the translation; we just fix them in the text. It's because the translation was created specifically for UD, hence an error in the translation is similar-level issue as an annotation error.

**Comment by dan-zeman** [comment]
> @dan-zeman Do you know why the update I just pushed hasn't fixed the validation error?

The local copy of the repo on the validation server was somehow corrupted and could not be updated. Fixed now.
